"""Results of the 2026 NHL Entry Draft, in pick order.

Scraped from the Wikipedia draft page on 2026-09-19 and hand-checked: 7 rounds,
224 picks, contiguous 1-224. Vegas forfeited pick 63, which is carried here as
a row with no player so the pick numbering stays true to the draft board.

Each row: (pick, round, pick_in_round, player, pos, nationality, nhl_team,
via, club) - "via" is the team the pick was acquired from, blank if the team
drafted on its own pick; "club" is the college/junior/club team played for in
the draft year.
"""
DRAFT_YEAR = 2026
SEASON = "25/26"

PICKS = [
    (1, 1, 1, 'Gavin McKenna', 'LW', 'Canada', 'Toronto Maple Leafs', '', 'Penn State Nittany Lions (B1G)'),
    (2, 1, 2, 'Ivar Stenberg', 'LW', 'Sweden', 'San Jose Sharks', '', 'Frölunda HC (SHL)'),
    (3, 1, 3, 'Caleb Malhotra', 'C', 'Canada', 'Vancouver Canucks', '', 'Brantford Bulldogs (OHL)'),
    (4, 1, 4, 'Daxon Rudolph', 'D', 'Canada', 'Buffalo Sabres', 'Chicago', 'Prince Albert Raiders (WHL)'),
    (5, 1, 5, 'Alberts Smits', 'D', 'Latvia', 'New York Rangers', '', 'EHC Red Bull Munchen (DEL)'),
    (6, 1, 6, 'Carson Carels', 'D', 'Canada', 'Calgary Flames', '', 'Prince George Cougars (WHL)'),
    (7, 1, 7, 'Chase Reid', 'D', 'United States', 'Seattle Kraken', '', 'Sault Ste. Marie Greyhounds (OHL)'),
    (8, 1, 8, 'Viggo Bjorck', 'C', 'Sweden', 'Winnipeg Jets', '', 'Djurgårdens IF (SHL)'),
    (9, 1, 9, 'Keaton Verhoeff', 'D', 'Canada', 'San Jose Sharks', 'Florida via Ottawa', 'North Dakota Fighting Hawks (NCHC)'),
    (10, 1, 10, 'Wyatt Cullen', 'LW', 'United States', 'Nashville Predators', '', 'U.S. NTDP (USHL)'),
    (11, 1, 11, 'Tynan Lawrence', 'C', 'Canada', 'St. Louis Blues', '', 'Boston University Terriers (ECAC)'),
    (12, 1, 12, 'Alexander Command', 'C', 'Sweden', 'New Jersey Devils', '', 'Orebro HK (SHL)'),
    (13, 1, 13, 'Malte Gustafsson', 'D', 'Sweden', 'New York Islanders', '', 'HV71 (SHL)'),
    (14, 1, 14, 'Oscar Hemming', 'LW', 'Finland', 'Columbus Blue Jackets', '', 'Boston College Eagles (ECAC)'),
    (15, 1, 15, 'Nikita Klepov', 'RW', 'United States', 'Anaheim Ducks', 'Detroit via St. Louis', 'Saginaw Spirit (OHL)'),
    (16, 1, 16, 'Maddox Dagenais', 'C', 'Canada', 'St. Louis Blues', 'Washington', 'Quebec Remparts (QMJHL)'),
    (17, 1, 17, 'Ethan Belchetz', 'LW', 'Canada', 'Utah Mammoth', 'Los Angeles', 'Windsor Spitfires (OHL)'),
    (18, 1, 18, 'Oliver Suvanto', 'C', 'Finland', 'Washington Capitals', 'Anaheim', 'Tappara (Liiga)'),
    (19, 1, 19, 'Elton Hermansson', 'RW', 'Sweden', 'Los Angeles Kings', 'Utah', 'Modo Hockey (HockeyAllsvenskan)'),
    (20, 1, 20, 'Ilia Morozov', 'C', 'Russia', 'Buffalo Sabres', 'Edmonton via San Jose', 'Miami RedHawks (NCHC)'),
    (21, 1, 21, 'Ryan Lin', 'D', 'Canada', 'San Jose Sharks', 'Philadelphia', 'Vancouver Giants (WHL)'),
    (22, 1, 22, 'Liam Ruck', 'RW', 'Canada', 'Pittsburgh Penguins', '', 'Medicine Hat Tigers (WHL)'),
    (23, 1, 23, 'JP Hurlbert', 'LW', 'United States', 'Detroit Red Wings', 'Boston via Utah', 'Kamloops Blazers (WHL)'),
    (24, 1, 24, 'Adam Novotny', 'LW', 'Czech Republic', 'Vancouver Canucks', 'Minnesota', 'Peterborough Petes (OHL)'),
    (25, 1, 25, 'Jonas Lagerberg Hoen', 'RW', 'Sweden', 'Ottawa Senators', 'Tampa Bay via Seattle and Florida', 'Leksands IF (SHL)'),
    (26, 1, 26, 'Gleb Pugachyov', 'RW', 'Russia', 'Montreal Canadiens', 'Dallas via Carolina, NY Rangers and Vegas', 'Torpedo Nizhny Novgorod (KHL)'),
    (27, 1, 27, 'Maksim Sokolovskii', 'D', 'Russia', 'Philadelphia Flyers', 'Buffalo via San Jose', 'London Knights (OHL)'),
    (28, 1, 28, 'Marcus Nordmark', 'LW', 'Sweden', 'Anaheim Ducks', 'Montreal and Vegas', 'Djurgårdens IF (SHL)'),
    (29, 1, 29, 'Juho Piiparinen', 'D', 'Finland', 'Vegas Golden Knights', 'Colorado via NY Islanders, St. Louis and Anaheim', 'Tappara (Liiga)'),
    (30, 1, 30, 'Jack Hextall', 'C', 'United States', 'Calgary Flames', 'Vegas', 'Youngstown Phantoms (USHL)'),
    (31, 1, 31, 'Tommy Bleyl', 'D', 'United States', 'Nashville Predators', 'Carolina', 'Moncton Wildcats (QMJHL)'),
    (32, 1, 32, 'Jaxon Cover', 'LW', 'Cayman Islands', 'Ottawa Senators', '', 'London Knights (OHL)'),
    (33, 2, 1, 'Brooks Rogowski', 'C', 'United States', 'Vancouver Canucks', '', 'Oshawa Generals (OHL)'),
    (34, 2, 2, 'Xavier Villeneuve', 'D', 'Canada', 'Chicago Blackhawks', '', 'Blainville-Boisbriand Armada (QMJHL)'),
    (35, 2, 3, 'Ryan Roobroeck', 'C', 'Canada', 'Chicago Blackhawks', 'NY Rangers via Utah, Calgary and New Jersey', 'Niagara Ice Dogs (OHL)'),
    (36, 2, 4, 'Chase Harrington', 'RW', 'Canada', 'Calgary Flames', '', 'Spokane Chiefs (WHL)'),
    (37, 2, 5, 'Matias Vanhanen', 'LW', 'Finland', 'New Jersey Devils', 'Toronto via Chicago', 'Everett Silvertips (WHL)'),
    (38, 2, 6, 'Casey Mutryn', 'RW', 'United States', 'Seattle Kraken', '', 'U.S. NTDP (USHL)'),
    (39, 2, 7, 'Markus Ruck', 'C', 'Canada', 'Pittsburgh Penguins', 'Winnipeg', 'Medicine Hat Tigers (WHL)'),
    (40, 2, 8, 'Simas Ignatavicius', 'RW', 'Lithuania', 'Florida Panthers', '', 'Geneve-Servette HC (NL)'),
    (41, 2, 9, 'Niklas Aaram-Olsen', 'RW', 'Norway', 'Vancouver Canucks', 'San Jose', 'Orebro HK (SHL)'),
    (42, 2, 10, 'Tobias Trejbal', 'G', 'Czech Republic', 'Calgary Flames', 'Nashville via Carolina', 'Youngstown Phantoms (USHL)'),
    (43, 2, 11, 'Egor Shilov', 'C', 'Russia', 'Colorado Avalanche', 'St. Louis via Pittsburgh and Columbus', 'Victoriaville Tigres (QMJHL)'),
    (44, 2, 12, 'Nikita Shcherbakov', 'D', 'Russia', 'New Jersey Devils', '', 'Salavat Yulaev Ufa (KHL)'),
    (45, 2, 13, 'Jayden Kurtz', 'D', 'United States', 'Anaheim Ducks', 'NY Islanders via Chicago and Buffalo', 'Rogers Royals (USHS-MN)'),
    (46, 2, 14, 'Liam Lefebvre', 'C', 'Canada', 'Los Angeles Kings', 'Columbus via Montreal', 'Chicoutimi Saguenéens (QMJHL)'),
    (47, 2, 15, 'Victor Plante', 'LW', 'United States', 'Detroit Red Wings', '', 'U.S. NTDP (USHL)'),
    (48, 2, 16, 'Ryder Cali', 'LW', 'Canada', 'Florida Panthers', 'Washington', 'North Bay Battalion (OHL)'),
    (49, 2, 17, 'Adam Goljer', 'D', 'Slovakia', 'Los Angeles Kings', '', 'HK Dukla Trencin (Slovak Extraliga)'),
    (50, 2, 18, 'Mathis Preston', 'RW', 'Canada', 'Anaheim Ducks', '', 'Vancouver Giants (WHL)'),
    (51, 2, 19, 'William Hakansson', 'D', 'Sweden', 'Carolina Hurricanes', 'Utah via Calgary', 'Lulea HF (SHL)'),
    (52, 2, 20, 'Oleg Kulebyakin', 'LW', 'Russia', 'Tampa Bay Lightning', 'Edmonton', 'Halifax Mooseheads (QMJHL)'),
    (53, 2, 21, 'Brek Liske', 'D', 'Canada', 'Philadelphia Flyers', '', 'Everett Silvertips (WHL)'),
    (54, 2, 22, 'Tomas Galvas', 'D', 'Czech Republic', 'Pittsburgh Penguins', '', 'Bílí Tygři Liberec (Czech Extraliga)'),
    (55, 2, 23, 'Alan Shaikhlislamov', 'D', 'Russia', 'Calgary Flames', 'Ottawa via Utah', 'Tolpar Ufa (MHL)'),
    (56, 2, 24, 'Yuri Ivanov', 'G', 'Russia', 'Boston Bruins', '', 'JHC Spartak (MHL)'),
    (57, 2, 25, 'Timofei Runtso', 'D', 'United States', 'Montreal Canadiens', 'Carolina via Nashville and Minnesota', 'Victoria Royals (WHL)'),
    (58, 2, 26, 'Rudolfs Berzkalns', 'C', 'Latvia', 'Edmonton Oilers', 'Tampa Bay', 'Muskegon Lumberjacks (USHL)'),
    (59, 2, 27, 'Jakub Vanecek', 'D', 'Czech Republic', 'Dallas Stars', '', 'Tri-City Americans (WHL)'),
    (60, 2, 28, 'Alexander Bilecki', 'D', 'Canada', 'Toronto Maple Leafs', 'Buffalo via Ottawa and Los Angeles', 'Kitchener Rangers (OHL)'),
    (61, 2, 29, 'Wiggo Sorensson', 'D', 'Sweden', 'Carolina Hurricanes', 'Montreal', 'Boro/Vetlanda HC (HockeyEttan)'),
    (62, 2, 30, 'Martin Psohlavec', 'G', 'Czech Republic', 'Philadelphia Flyers', 'Colorado via San Jose', 'HC Energie Karlovy Vary (Czech Extraliga)'),
    (63, 2, 31, '(forfeited)', '', '', 'Vegas Golden Knights', '', ''),
    (64, 2, 32, 'Ben Macbeath', 'D', 'Canada', 'New York Rangers', 'Carolina', 'Calgary Hitmen (WHL)'),
    (65, 3, 1, 'Joe Iginla', 'RW', 'Canada', 'Calgary Flames', 'Vancouver', 'Vancouver Giants (WHL)'),
    (66, 3, 2, 'Samu Alalauri', 'D', 'Finland', 'Chicago Blackhawks', '', 'Lahti Pelicans (U20 SM-sarja)'),
    (67, 3, 3, 'Danai Shaiikov', 'G', 'Kazakhstan', 'New York Rangers', '', 'Gatineau Olympiques (QMJHL)'),
    (68, 3, 4, 'Zachary Lansard', 'RW', 'Canada', 'Carolina Hurricanes', 'Calgary', 'Regina Pats (WHL)'),
    (69, 3, 5, 'Ethan MacKenzie', 'D', 'Canada', 'Toronto Maple Leafs', '', 'Edmonton Oil Kings (WHL)'),
    (70, 3, 6, 'Dmitri Borichev', 'G', 'Russia', 'Nashville Predators', 'Seattle via Dallas', 'JHC Loko (MHL)'),
    (71, 3, 7, 'Samuel Hrenak', 'G', 'Slovakia', 'Winnipeg Jets', '', 'Fargo Force (USHL)'),
    (72, 3, 8, 'Adam Nemec', 'LW', 'Slovakia', 'Ottawa Senators', 'Florida', 'Sudbury Wolves (OHL)'),
    (73, 3, 9, 'Zach Olsen', 'RW', 'Canada', 'Toronto Maple Leafs', 'San Jose via Pittsburgh, Detroit, and St. Louis', 'Saskatoon Blades (WHL)'),
    (74, 3, 10, 'Beckett Hamilton', 'C', 'United States', 'Colorado Avalanche', 'Nashville', 'Red Deer Rebels (WHL)'),
    (75, 3, 11, 'Luke Schairer', 'D', 'United States', 'St. Louis Blues', '', 'U.S. NTDP (USHL)'),
    (76, 3, 12, 'Mans Gudmundsson', 'D', 'Sweden', 'Toronto Maple Leafs', 'New Jersey via NY Islanders and St. Louis', 'Färjestad BK (J20 Nationell)'),
    (77, 3, 13, 'Charlie Morrison', 'D', 'Canada', 'New York Rangers', 'NY Islanders', 'Quebec Remparts (QMJHL)'),
    (78, 3, 14, 'Dmitri Ivchenko', 'G', 'Russia', 'Vancouver Canucks', 'Columbus', 'Omskie Yastreby (MHL)'),
    (79, 3, 15, 'Michal Orsulak', 'G', 'Czech Republic', 'Detroit Red Wings', '', 'Prince Albert Raiders (WHL)'),
    (80, 3, 16, 'Blake Zielinski', 'C', 'United States', 'Los Angeles Kings', 'Washington via Ottawa', 'Des Moines Buccaneers (USHL)'),
    (81, 3, 17, 'Tomas Chrenko', 'C', 'Slovakia', 'New York Rangers', 'Los Angeles', 'HK Nitra (Slovak Extraliga)'),
    (82, 3, 18, 'Rian Chudzinski', 'RW', 'United States', 'Anaheim Ducks', '', 'Moncton Wildcats (QMJHL)'),
    (83, 3, 19, 'Adam Andersson', 'C', 'Sweden', 'Minnesota Wild', 'Utah via Los Angeles', 'Leksands IF (J20 Nationell)'),
    (84, 3, 20, 'Malcom Gastrin', 'LW', 'Sweden', 'Edmonton Oilers', '', 'Modo Hockey (J20 Nationell)'),
    (85, 3, 21, 'Juuso Ainasto', 'G', 'Finland', 'Toronto Maple Leafs', 'Philadelphia', 'Jokerit (U20 SM-sarja)'),
    (86, 3, 22, 'Pierce Mbuyi', 'LW', 'Canada', 'Pittsburgh Penguins', '', 'Owen Sound Attack (OHL)'),
    (87, 3, 23, 'Oscar Holmertz', 'C', 'Sweden', 'Ottawa Senators', '', 'Linköping HC (J20 Nationell)'),
    (88, 3, 24, 'Nils Bartholdsson', 'RW', 'Sweden', 'Boston Bruins', '', 'Rögle BK (J20 Nationell)'),
    (89, 3, 25, 'Yegor Rybkin', 'G', 'Russia', 'Los Angeles Kings', 'Minnesota', 'Chaika Nizhny Novgorod (MHL)'),
    (90, 3, 26, 'Tomas Kralovic', 'D', 'Slovakia', 'Tampa Bay Lightning', '', 'HC Slovan Bratislava (Slovak Extraliga)'),
    (91, 3, 27, 'Louis-Felix Bourque', 'RW', 'Canada', 'Ottawa Senators', 'Dallas via Carolina and Los Angeles', 'Drummondville Voltigeurs (QMJHL)'),
    (92, 3, 28, 'Ben Wilmott', 'C', 'United States', 'Vegas Golden Knights', 'New York via Buffalo', 'Barrie Colts (OHL)'),
    (93, 3, 29, 'Cooper Cleaves', 'D', 'United States', 'Montreal Canadiens', '', 'Dartmouth Big Green (ECAC)'),
    (94, 3, 30, 'Alessandro Di Iorio', 'C', 'Canada', 'Columbus Blue Jackets', 'Colorado via Minnesota', 'Sarnia Sting (OHL)'),
    (95, 3, 31, 'Sean Burick', 'D', 'United States', 'Vegas Golden Knights', '', 'Penticton Vees (WHL)'),
    (96, 3, 32, 'Adam Valentini', 'C', 'Canada', 'Utah Mammoth', 'Carolina', 'Michigan Wolverines (B1G)'),
    (97, 4, 1, 'Yaroslav Bryzgalov', 'LW', 'Belarus', 'Vancouver Canucks', '', 'Medicine Hat Tigers (WHL)'),
    (98, 4, 2, 'Jonas Kemps', 'D', 'United States', 'Florida Panthers', 'Chicago', 'Chicago Steel (USHL)'),
    (99, 4, 3, 'Viktor Fedorov', 'C', 'Russia', 'Seattle Kraken', 'NY Rangers via Columbus', 'Torpedo Nizhny Novgorod (KHL)'),
    (100, 4, 4, 'Egor Barabanov', 'C', 'Russia', 'Calgary Flames', '', 'Saginaw Spirit (OHL)'),
    (101, 4, 5, 'Tyus Sparks', 'C', 'United States', 'Washington Capitals', 'Toronto via Minnesota and Columbus', 'Spokane Chiefs (WHL)'),
    (102, 4, 6, 'Spencer Bowes', 'LW', 'Canada', 'New York Rangers', 'Seattle', 'Ottawa 67’s (OHL)'),
    (103, 4, 7, 'Thomas Vandenberg', 'C', 'Canada', 'Los Angeles Kings', 'Winnipeg via New Jersey and Montreal', 'Ottawa 67’s (OHL)'),
    (104, 4, 8, 'Matvei Kotkov', 'RW', 'Russia', 'Boston Bruins', 'Florida via San Jose', 'Loko Yaroslavl (MHL)'),
    (105, 4, 9, 'Michael Berchild', 'LW', 'United States', 'Carolina Hurricanes', 'San Jose', 'U.S. NTDP (USHL)'),
    (106, 4, 10, 'Jakub Floris', 'D', 'Slovakia', 'Nashville Predators', '', 'Lukko (Liiga)'),
    (107, 4, 11, 'Landon Nycz', 'D', 'United States', 'St. Louis Blues', '', 'UMass (H-East)'),
    (108, 4, 12, 'Adam Levac', 'C', 'Canada', 'Detroit Red Wings', 'New Jersey', 'Peterborough Petes (OHL)'),
    (109, 4, 13, 'Lincoln Kuehne', 'D', 'United States', 'New York Islanders', '', 'Arizona State (NCHC)'),
    (110, 4, 14, 'Elliot Lennon', 'G', 'Canada', 'Ottawa Senators', 'Columbus via Detroit', 'Deerfield Big Green (HS-MA)'),
    (111, 4, 15, 'Parker Von Richter', 'D', 'Canada', 'Pittsburgh Penguins', 'Detroit via Anaheim and Boston', 'Barrie Colts (OHL)'),
    (112, 4, 16, 'Kayden Lemire', 'RW', 'Canada', 'Minnesota Wild', 'Washington via Columbus', 'Prince George Cougars (WHL)'),
    (113, 4, 17, 'Jonah Sivertson', 'RW', 'Canada', 'Vegas Golden Knights', 'Los Angeles via Montreal', 'Prince Albert Raiders (WHL)'),
    (114, 4, 18, 'Patriks Plumins', 'G', 'Latvia', 'Toronto Maple Leafs', 'Anaheim via Seattle', 'HK Zemgale/LBTU (LHHL)'),
    (115, 4, 19, 'Carl Axelsson', 'G', 'Sweden', 'Utah Mammoth', '', 'Muskegon Lumberjacks (USHL)'),
    (116, 4, 20, 'Zach Wooten', 'LW', 'United States', 'Winnipeg Jets', 'Edmonton via Boston and Buffalo', 'Green Bay Gamblers (USHL)'),
    (117, 4, 21, 'Brayden Klimpke', 'D', 'Canada', 'Montreal Canadiens', 'Philadelphia via Anaheim and Vegas', 'Saskatoon Blades (WHL)'),
    (118, 4, 22, 'Justin Graf', 'LW', 'United States', 'Nashville Predators', 'Pittsburgh', 'Cedar Rapids RoughRiders (USHL)'),
    (119, 4, 23, 'Lavr Gashilov', 'C', 'Russia', 'New Jersey Devils', 'Ottawa via Chicago', 'JHC Atvo (MHL)'),
    (120, 4, 24, 'Marek Sklenicka', 'G', 'Czech Republic', 'Philadelphia Flyers', 'Boston via San Jose', 'Seattle Thunderbirds (WHL)'),
    (121, 4, 25, 'Evan Jardine', 'LW', 'United States', 'Columbus Blue Jackets', 'Minnesota', 'Youngstown Phantoms (USHL)'),
    (122, 4, 26, 'Oscar Olsson', 'LW', 'Sweden', 'Boston Bruins', 'Tampa Bay', 'Orebro HK (SHL)'),
    (123, 4, 27, 'Vladimir Proskurin', 'G', 'Russia', 'St. Louis Blues', 'Dallas via New Jersey', 'MHK Atlant Mytischi (MHL)'),
    (124, 4, 28, 'Olivers Murnieks', 'C', 'Latvia', 'Buffalo Sabres', '', 'Saint John Sea Dogs (QMJHL)'),
    (125, 4, 29, 'Ryder Fetterolf', 'G', 'United States', 'Carolina Hurricanes', 'Montreal', 'Ottawa 67’s (OHL)'),
    (126, 4, 30, 'Tobias Tvrznik', 'G', 'Czech Republic', 'Colorado Avalanche', '', 'Wenatchee Wild (WHL)'),
    (127, 4, 31, 'Brady Knowling', 'G', 'Canada', 'San Jose Sharks', 'Vegas via Washington', 'U.S. NTDP (USHL)'),
    (128, 4, 32, 'Axel Elofsson', 'D', 'Sweden', 'Colorado Avalanche', 'Carolina', 'Orebro HK (SHL)'),
    (129, 5, 1, 'Connor Davis', 'RW', 'Canada', 'Vancouver Canucks', '', 'Cedar Rapids RoughRiders (USHL)'),
    (130, 5, 2, 'Theodor Knights', 'D', 'Sweden', 'Utah Mammoth', 'Chicago', 'MoDo Hockey U20 (U20 Nationell)'),
    (131, 5, 3, 'Finn Kearns', 'D', 'Canada', 'Seattle Kraken', 'New York Rangers', 'St. Andrews Saints (HS-ON)'),
    (132, 5, 4, 'Simon Katolicky', 'LW', 'Finland', 'Calgary Flames', '', 'Sarnia Sting (OHL)'),
    (133, 5, 5, 'Andrew Robinson', 'D', 'Canada', 'Edmonton Oilers', 'Toronto via Tampa Bay', 'Windsor Spitfire (OHL)'),
    (134, 5, 6, 'Morgan Anderberg', 'C', 'Sweden', 'Tampa Bay Lightning', 'Seattle', 'Vaxjo Lakers (SHL)'),
    (135, 5, 7, 'Alexandre Talliefer', 'D', 'Canada', 'Winnipeg Jets', '', 'Quebec Remparts (QMJHL)'),
    (136, 5, 8, 'KJ Sauer', 'C', 'United States', 'Philadelphia Flyers', 'Florida', 'Andover Huskies (HS-MN)'),
    (137, 5, 9, 'Filip Ruzicka', 'G', 'Czech Republic', 'Minnesota Wild', 'San Jose', 'Brandon Wheat Kings (WHL)'),
    (138, 5, 10, 'Philip Hemmyr', 'LW', 'Sweden', 'Nashville Predators', '', 'IF Bjorkloven (SHL)'),
    (139, 5, 11, 'Nicholas Bogas', 'D', 'United States', 'St. Louis Blues', '', 'U.S. NTDP (USHL)'),
    (140, 5, 12, 'Cole Tuminaro', 'D', 'United States', 'Colorado Avalanche', 'New Jersey', 'Chicago Steel (USHL)'),
    (141, 5, 13, 'Vladimir Dravecky', 'D', 'Czech Republic', 'New York Islanders', '', 'Brantford Bulldogs (OHL)'),
    (142, 5, 14, 'Parker Snell', 'G', 'Canada', 'Columbus Blue Jackets', '', 'Edmonton Oil Kings (WHL)'),
    (143, 5, 15, 'Beckham Edwards', 'C', 'Canada', 'Detroit Red Wings', '', 'Sarnia Sting (OHL)'),
    (144, 5, 16, 'Brian McFadden', 'D', 'United States', 'Washington Capitals', '', 'Thayer Tigers (HS-MA)'),
    (145, 5, 17, 'Vertti Svensk', 'D', 'Finland', 'Los Angeles Kings', '', 'SaiPa (Liiga)'),
    (146, 5, 18, 'Eric Frossard', 'D', 'Canada', 'Anaheim Ducks', '', 'Guelph Storm (OHL)'),
    (147, 5, 19, 'Florent Houle', 'RW', 'Canada', 'Utah Mammoth', '', 'Sherbrooke Phoenix (QMJHL)'),
    (148, 5, 20, 'Luken Huff', 'D', 'United States', 'Seattle Kraken', 'Edmonton via Nashville and New York Rangers', 'Cedar Rapids RoughRiders (USHL)'),
    (149, 5, 21, 'Daniil Rusakovich', 'G', 'Belarus', 'New Jersey Devils', 'Philadelphia via Colorado', 'Dinamo-Shinnik Bobruysk (MHL)'),
    (150, 5, 22, 'Carter Stevens', 'RW', 'Canada', 'St. Louis Blues', 'Pittsburgh', 'Guelph Storm (OHL)'),
    (151, 5, 23, 'Harris Pangretitsch', 'D', 'Canada', 'Ottawa Senators', '', 'Sault Ste. Marie Greyhounds (OHL)'),
    (152, 5, 24, 'Theodore Lechner', 'D', 'United States', 'Colorado Avalanche', 'Boston', 'Holy Angels Stars (HS-MN)'),
    (153, 5, 25, 'Giorgois Pantelas', 'D', 'Canada', 'Los Angeles Kings', 'Minnesota', 'Brandon Wheat Kings (WHL)'),
    (154, 5, 26, 'Cooper Soller', 'C', 'United States', 'Tampa Bay Lightning', '', 'Sioux Falls Stampede (USHL)'),
    (155, 5, 27, 'Ryan Brown', 'LW', 'Canada', 'Dallas Stars', '', 'London Knights (OHL)'),
    (156, 5, 28, 'Domán Szongoth', 'C', 'Hungary', 'Buffalo Sabres', '', 'KooKoo U20 (U20 SM-sarja)'),
    (157, 5, 29, 'Jacob Vandeven', 'D', 'Canada', 'Boston Bruins', 'Montreal via San Jose', 'Komoka Kings (GOJHL)'),
    (158, 5, 30, 'Cooper Williams', 'C', 'Canada', 'Toronto Maple Leafs', 'Colorado', 'Saskatoon Blades (WHL)'),
    (159, 5, 31, 'Will McLaughlin', 'D', 'Canada', 'Vegas Golden Knights', '', 'Portland Winterhawks (WHL)'),
    (160, 5, 32, 'Matvei Nikonovich', 'G', 'Belarus', 'Pittsburgh Penguins', 'Carolina via Nashville', 'Ladia Togliatti (MHL)'),
    (161, 6, 1, 'Yaroslav Fedoseyev', 'D', 'Russia', 'Toronto Maple Leafs', 'Vancouver Canucks', 'Belye Medvedi Chelyabinsk (MHL)'),
    (162, 6, 2, 'Andre Mondoux', 'D', 'Canada', 'New York Rangers', 'Chicago via Buffalo', 'Kingston Frontenacs (OHL)'),
    (163, 6, 3, 'Darian Anderson', 'RW', 'United States', 'New York Rangers', '', 'Flint Firebirds (OHL)'),
    (164, 6, 4, 'Bode Laylin', 'D', 'United States', 'Calgary Flames', '', 'Tri-City Storm (USHL)'),
    (165, 6, 5, 'Zachary Jovanoski', 'G', 'Canada', 'Carolina Hurricanes', 'Toronto', 'Guelph Storm (OHL)'),
    (166, 6, 6, 'Ola Palme', 'D', 'Sweden', 'Seattle Kraken', '', 'Växjö Lakers (SHL)'),
    (167, 6, 7, 'Landon Hafele', 'C', 'United States', 'Winnipeg Jets', '', 'Green Bay Gamblers (USHL)'),
    (168, 6, 8, 'Vilho Vanhatalo', 'RW', 'Finland', 'Florida Panthers', '', 'Tappara (Liiga)'),
    (169, 6, 9, 'Brody Pepoy', 'RW', 'United States', 'Toronto Maple Leafs', 'San Jose', 'Saginaw Spirit (OHL)'),
    (170, 6, 10, 'Roberto Henriquez', 'G', 'Slovakia', 'Boston Bruins', 'Nashville via Pittsburgh', 'Green Bay Gamblers (USHL)'),
    (171, 6, 11, 'Lars Steiner', 'RW', 'Switzerland', 'St. Louis Blues', '', 'Rouyn-Noranda Huskies (QMJHL)'),
    (172, 6, 12, 'Luke Wilfley', 'C', 'United States', 'New Jersey Devils', '', 'Portland Winterhawks (WHL)'),
    (173, 6, 13, 'Artyon Matyuk', 'C', 'Russia', 'New York Islanders', '', 'Chaika Nizhny Novgorod (MHL)'),
    (174, 6, 14, 'Jake Gustafson', 'C', 'United States', 'San Jose Sharks', 'Columbus via Philadelphia', 'Portland Winterhawks (WHL)'),
    (175, 6, 15, 'Luka Arkko', 'LW', 'Finland', 'Detroit Red Wings', '', 'Pelicans U20 (U20 SM-sarja)'),
    (176, 6, 16, 'Lucian Bernat', 'RW', 'Slovakia', 'Vancouver Canucks', 'Washington', 'Tappara U20 (U20 SM-sarja)'),
    (177, 6, 17, 'Alex Kostov', 'RW', 'Canada', 'Los Angeles Kings', '', 'Flint Firebirds (OHL)'),
    (178, 6, 18, 'Gleb Peshkov', 'G', 'Russia', 'Anaheim Ducks', '', 'Taifun Primorsky Krai (MHL)'),
    (179, 6, 19, 'Benjamin Cossette-Ayotte', 'D', 'Canada', 'Nashville Predators', 'Utah', "Val-d'Or Foreurs (QMJHL)"),
    (180, 6, 20, 'Caden Harvey', 'C', 'United States', 'Edmonton Oilers', '', 'Windsor Spitfire (OHL)'),
    (181, 6, 21, 'Cole Zurawski', 'RW', 'Canada', 'Florida Panthers', 'Philadelphia', 'Owen Sound Attack (OHL)'),
    (182, 6, 22, 'Anttoni Uronen', 'C', 'Finland', 'Columbus Blue Jackets', 'Pittsburgh', 'HIFK Hockey (Liiga)'),
    (183, 6, 23, 'Alexander Grunin', 'D', 'Russia', 'Ottawa Senators', '', 'Sibirskie Snaipery Novosibirsk (MHL)'),
    (184, 6, 24, 'Samuel Eriksson', 'D', 'Sweden', 'Vancouver Canucks', 'Boston via Minnesota', 'Färjestad BK U20 (U20 Nationell)'),
    (185, 6, 25, 'Jonas Woo', 'D', 'Canada', 'Columbus Blue Jackets', 'Minnesota', 'Medicine Hat Tigers (WHL)'),
    (186, 6, 26, 'Stepan Shurygin', 'G', 'Russia', 'Tampa Bay Lightning', '', 'Saginaw Spirit (OHL)'),
    (187, 6, 27, 'Anton Emil Wilde Larsen', 'G', 'Denmark', 'Dallas Stars', '', 'Frederikshavn White Hawks (Metal Liagen)'),
    (188, 6, 28, 'Dylan Dumont', 'RW', 'Canada', 'Buffalo Sabres', '', 'Drummondville Voltigeurs (QMJHL)'),
    (189, 6, 29, 'Parker Trottier', 'LW', 'United States', 'Montreal Canadiens', '', 'U.S. NTDP (USHL)'),
    (190, 6, 30, 'Wesley Royston', 'RW', 'Canada', 'Montreal Canadiens', 'Colorado via Ottawa and Los Angeles', 'Owen Sound Attack (OHL)'),
    (191, 6, 31, 'Matthew Minchak', 'G', 'United States', 'Vegas Golden Knights', '', 'Kingston Frontenacs (OHL)'),
    (192, 6, 32, 'Noah Kosick', 'C', 'Canada', 'Anaheim Ducks', 'Carolina', 'Seattle Thunderbirds (WHL)'),
    (193, 7, 1, 'Ivan Patrikhayev', 'D', 'Russia', 'New York Rangers', 'Vancouver', 'CSKA Moscow (KHL)'),
    (194, 7, 2, 'Alexander Ivanov', 'D', 'Russia', 'Chicago Blackhawks', '', 'Bars Kazan (VHL)'),
    (195, 7, 3, 'Shawn Carrier', 'LW', 'Canada', 'Colorado Avalanche', 'NY Rangers via Nashville', 'Halifax Mooseheads (QMJHL)'),
    (196, 7, 4, 'Myles Brosnan', 'D', 'United States', 'Detroit Red Wings', 'Calgary', 'Dexter Southfield Shield (HS-MA)'),
    (197, 7, 5, 'Jasper Kuhta', 'C', 'Finland', 'Dallas Stars', 'Toronto', "Ottawa 67's (OHL)"),
    (198, 7, 6, 'Rylan Singh', 'D', 'Canada', 'Seattle Kraken', '', 'Guelph Storm (OHL)'),
    (199, 7, 7, "Noa Ta'amu", 'D', 'United States', 'Winnipeg Jets', '', 'Edmonton Oil Kings (WHL)'),
    (200, 7, 8, 'William Sorbrand', 'C', 'Sweden', 'Chicago Blackhawks', 'Florida', 'Timra IK (SHL)'),
    (201, 7, 9, 'Alexander Karmanov', 'D', 'Moldova', 'San Jose Sharks', '', 'North Bay Battalion (OHL)'),
    (202, 7, 10, 'Charlie Puglisi', 'C', 'United States', 'Nashville Predators', '', 'Winchendon Wapitis (HS-MA)'),
    (203, 7, 11, 'Colin Fitzgerald', 'C', 'Canada', 'St. Louis Blues', '', 'Sault Ste. Marie Greyhounds (OHL)'),
    (204, 7, 12, 'William Tomko', 'C', 'United States', 'Seattle Kraken', 'New Jersey', 'Sioux City Musketeers (USHL)'),
    (205, 7, 13, 'Bobby Cowan', 'RW', 'United States', 'New York Islanders', '', 'Western Michigan Broncos (NCHC)'),
    (206, 7, 14, 'Filip Novak', 'LW', 'Czech Republic', 'Columbus Blue Jackets', '', 'HC Sparta Praha (Czech Extraliga)'),
    (207, 7, 15, 'Noel Pakarinen', 'LW', 'Finland', 'Vegas Golden Knights', 'Detroit', 'Kiekko-Espoo (U20 SM-sarja)'),
    (208, 7, 16, 'Logan Stuart', 'C', 'United States', 'Washington Capitals', '', 'U.S. NTDP (USHL)'),
    (209, 7, 17, 'Tobias Krestan', 'RW', 'Germany', 'Los Angeles Kings', '', 'HV71 (J20 Nationell)'),
    (210, 7, 18, 'Jimmy Rieber', 'D', 'United States', 'Anaheim Ducks', '', 'Waterloo Black Hawks (USHL)'),
    (211, 7, 19, 'Artyom Prima', 'RW', 'Russia', 'Utah Mammoth', '', 'Omaha Lancers (USHL)'),
    (212, 7, 20, 'Ryan Cameron', 'G', 'United States', 'Edmonton Oilers', '', 'Cedar Rapids RoughRiders (USHL)'),
    (213, 7, 21, 'Max Laatikainen', 'D', 'Finland', 'Philadelphia Flyers', '', 'Kiekko-Espoo (U20 SM-sarja)'),
    (214, 7, 22, 'Ondrej Ruml', 'D', 'Czech Republic', 'Colorado Avalanche', 'Pittsburgh', "Ottawa 67's (OHL)"),
    (215, 7, 23, 'Alexandre Raymond', 'G', 'Canada', 'Colorado Avalanche', 'Ottawa', 'Rouyn-Noranda Huskies (QMJHL)'),
    (216, 7, 24, 'Cullen McCrate', 'D', 'United States', 'Boston Bruins', '', 'Fargo Force (USHL)'),
    (217, 7, 25, 'Louis-Antoine Denault', 'G', 'Canada', 'Florida Panthers', 'Minnesota', 'Newfoundland Regiment (QMJHL)'),
    (218, 7, 26, 'Max Vilen', 'D', 'Sweden', 'Tampa Bay Lightning', '', 'Moncton Wildcats (QMJHL)'),
    (219, 7, 27, 'Mikhail Cherepanov', 'D', 'Russia', 'Dallas Stars', '', 'New Hampshire Mountain Kings (NAHL)'),
    (220, 7, 28, 'John Parsons', 'G', 'United States', 'Winnipeg Jets', 'Buffalo', 'Providence Friars (HE)'),
    (221, 7, 29, 'Jean-Samuel Daigneault', 'D', 'Canada', 'Montreal Canadiens', '', 'Muskegon Lumberjacks (USHL)'),
    (222, 7, 30, 'Quinn McKenzie', 'C', 'United States', 'New Jersey Devils', 'Colorado', 'Sault Ste. Marie Greyhounds (OHL)'),
    (223, 7, 31, 'Lucas Ambrosio', 'D', 'Canada', 'Los Angeles Kings', 'Vegas', 'Erie Otters (OHL)'),
    (224, 7, 32, 'Tyler Deakos', 'RW', 'Canada', 'Montreal Canadiens', 'Carolina', 'Waterloo Black Hawks (USHL)'),
]

# Drafting clubs as the Fantrax export abbreviates them, so a pick can be
# checked against the club a player is actually in.
TEAM_ABBR = {
    "Anaheim Ducks": "ANA", "Boston Bruins": "BOS", "Buffalo Sabres": "BUF",
    "Calgary Flames": "CGY", "Carolina Hurricanes": "CAR",
    "Chicago Blackhawks": "CHI", "Colorado Avalanche": "COL",
    "Columbus Blue Jackets": "CBJ", "Dallas Stars": "DAL",
    "Detroit Red Wings": "DET", "Edmonton Oilers": "EDM",
    "Florida Panthers": "FLA", "Los Angeles Kings": "LAK",
    "Minnesota Wild": "MIN", "Montreal Canadiens": "MTL",
    "Nashville Predators": "NSH", "New Jersey Devils": "NJD",
    "New York Islanders": "NYI", "New York Rangers": "NYR",
    "Ottawa Senators": "OTT", "Philadelphia Flyers": "PHI",
    "Pittsburgh Penguins": "PIT", "San Jose Sharks": "SJS",
    "Seattle Kraken": "SEA", "St. Louis Blues": "STL",
    "Tampa Bay Lightning": "TBL", "Toronto Maple Leafs": "TOR",
    "Utah Mammoth": "UTA", "Vancouver Canucks": "VAN",
    "Vegas Golden Knights": "VGK", "Washington Capitals": "WSH",
    "Winnipeg Jets": "WPG"}
